from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 420)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 321, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.CSV = QtWidgets.QWidget()
        self.CSV.setObjectName("CSV")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.CSV)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 160, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=self.CSV)
        self.label.setGeometry(QtCore.QRect(40, 30, 47, 20))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.CSV)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 70, 161, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(parent=self.CSV)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 47, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.CSV)
        self.label_3.setGeometry(QtCore.QRect(66, 110, 181, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.CSV)
        self.pushButton.setGeometry(QtCore.QRect(110, 220, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.CSV, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 70, 161, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 91, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 110, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 110, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 220, 91, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 30, 161, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 91, 20))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionyoo = QtGui.QAction(parent=MainWindow)
        self.actionyoo.setObjectName("actionyoo")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grade Curver"))
        self.label.setText(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Output"))
        self.label_3.setText(_translate("MainWindow", "Errors"))
        self.pushButton.setText(_translate("MainWindow", "SUBMIT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CSV), _translate("MainWindow", "CSV Input"))
        self.lineEdit_3.setText(_translate("MainWindow", "John 25"))
        self.label_5.setText(_translate("MainWindow", "Name and Grade"))
        self.pushButton_2.setText(_translate("MainWindow", "Next student"))
        self.pushButton_3.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_4.setText(_translate("MainWindow", "SUBMIT"))
        self.label_4.setText(_translate("MainWindow", "Output filename"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Manual Input"))
        self.actionyoo.setText(_translate("MainWindow", "yoo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())